---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: api-ro
  namespace: api-ns
  annotations:
    notifications.argoproj.io/subscribe.on-rollout-completed.slack: general

spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
      name: api-po
  strategy:
    canary:
      stableService: api-svc
      canaryService: canary-api-svc
      steps:
      - setWeight: 25
      - setCanaryScale: 
          weight: 25
      - setHeaderRoute:
          name: api-canary
          match:
          - headerName: X-Version
            headerValue:
              exact: canary
      - pause: {}
      trafficRouting:
        managedRoutes:
        - name: api-canary
        plugins:
          argoproj-labs/gatewayAPI:
            httpRoutes:
            - name: api-httproute
              useHeaderRoutes: true
            namespace: api-ns
  template:
    metadata:
      labels:
        app: api
        name: api-po
    spec:
      containers:
      - name: api-container
        image: chukmunnlee/fake-api:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000


