---
apiVersion: v1
kind: Service
metadata:
  name: minio-hsvc
  namespace: playground
  labels:
    app: minio
    labels: minio-hsvc
spec:
  clusterIP: None
  selector:
    app: minio
    name: minio-po
  ports:
    - name: minio-data 
      port: 9000
      targetPort: 9000
    - name: minio-web 
      port: 9001
      targetPort: 9001

---
#apiVersion: apps/v1
#kind: StatefulSet
#metadata:
#  name: minio-sts
#  namespace: playground
#  labels:
#    app: minio
#    name: minio-sts
#spec:
#  replicas: 3
#  serviceName: minio-hsvc
