---
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: k8s-es
  namespace: playground
spec:
  eventBusName: jetstream-eb
  template:
    metadata:
      name: k8s-es-po
    serviceAccountName: playground-sa
