---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: playground-sa
  namespace: playground

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: playground-cr
rules:
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - '*'

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: playground-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: playground-cr
subjects:
- kind: ServiceAccount
  name: playground-sa
  namespace: playground

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: playground-r
  namespace: playground
rules:
- apiGroups:
  - argoproj.io
  resources:
  - workflows
  - workflowtemplates
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - '*'

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: playground-rb
  namespace: playground
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: playground-r
subjects:
- kind: ServiceAccount
  name: playground-sa
  namespace: playground

