---
apiVersion: v1
kind: ConfigMap
metadata:
  name: httpbin-cm
  namespace: playground
  labels:
    app: httpbin
    name: httpbin-cm
data:
  Caddyfile: |
    :{$PROXY_PORT} {
    	reverse_proxy localhost:{$TARGET_PORT}
    	log {
    		output stdout
    		format json
    	}
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin-deploy
  namespace: playground
  labels:
    app: httpbin
    name: httpbin-deploy

spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin
      name: httpbin-po
  template:
    metadata:
      name: httpbin-po
      labels:
        app: httpbin
        name: httpbin-po
    spec:
      volumes:
      - name: httpbin-vol
        configMap:
          name: httpbin-cm

      containers:
      - name: caddy-container
        image: caddy
        imagePullPolicy: IfNotPresent
        args:
        - caddy
        - run
        - --config
        - /opt/tmp/Caddyfile
        env:
        - name: PROXY_PORT
          value: "2080"
        - name: TARGET_PORT
          value: "80"
        ports:
        - name: caddy-port 
          containerPort: 2080
        volumeMounts:
        - name: httpbin-vol
          mountPath: /opt/tmp
          readOnly: true

      - name: httpbin-container
        image: kennethreitz/httpbin@sha256:599fe5e5073102dbb0ee3dbb65f049dab44fa9fc251f6835c9990f8fb196a72b
        imagePullPolicy: IfNotPresent
        env:
        - name: GUNICORN_CMD_ARGS
          value: "--capture-output --error-logfile - --access-logfile - --access-logformat '%(h)s %(t)s %(r)s %(s)s Host: %({Host}i)s}'"
        ports:
        - name: httpbin-port 
          containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: httpbin-svc
  namespace: playground
  labels:
    app: httpbin
    name: httpbin-svc
spec:
  type: ClusterIP
  selector:
    app: httpbin
    name: httpbin-po
  ports:
  - port: 8080
    targetPort: caddy-port
