---
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: webhook-es
  namespace: playground

spec:
  eventBusName: kafka-eb
  webhook:
    simple:
      endpoint: /notify
      port: "12000"
      method: POST

---
apiVersion: v1
kind: Service
metadata:
  name: webhook-svc
  namespace: playground
  labels:
    app: webhook-svc
spec:
  type: ClusterIP
  selector:
    eventsource-name: webhook-es
    owner-name: webhook-es
  ports:
  - port: 12000
    targetPort: 12000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webhook-ing
  namespace: playground
spec:
  ingressClassName: nginx
  rules:
  - host: webhook-192.168.39.119.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: webhook-svc
            port:
              number: 12000
