---
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: webhook-es
  namespace: playground

spec:
  eventBusName: kafka-eb
  webhook:
    simple:
      endpoint: /notify
      port: "12000"
      method: POST

---
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webhook-sn
  namespace: playground
spec:
  eventBusName: kafka-eb
  dependencies:
  - name: message
    eventSourceName: webhook-es
    eventName: simple
  triggers:
  - template:
      name: http-post
      http:
        url: http://httpbin-svc.playground.svc.cluster.local:8080/post
        method: POST
        payload:
        - src:
            dependencyName: message
            dataKey: body.message
          dest: message
        - src:
            dependencyName: message
            contextKey: datacontenttype
          dest: content-type

---
apiVersion: v1
kind: Service
metadata:
  name: webhook-svc
  namespace: playground
  labels:
    app: webhook-svc
spec:
  type: ClusterIP
  selector:
    eventsource-name: webhook-es
    owner-name: webhook-es
  ports:
  - port: 12000
    targetPort: 12000

