---
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webhook-sn
  namespace: playground
spec:
  eventBusName: kafka-eb
  dependencies:
  - name: message
    eventSourceName: webhook-es
    eventName: simple
    transform:
      script: |-
        local form = ''

        for k, v in pairs(event.body.message) do
          form = form .. '&' .. k .. '=' .. v
        end

        event.body.form = string.sub(form, 2, #form)

        return event

  triggers:
  - template:
      name: http-post
      http:
        url: http://shttpbin-svc.playground.svc.cluster.local:8080/post
        method: POST
        headers:
          Content-Type: application/x-www-form-urlencoded
          #Content-Type: application/json
        payload:
        - src:
            dependencyName: message
            dataKey: body.form
          dest: ".0"
