---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-server-ing
  namespace: argocd
spec:
  rules:
  - host: argocd-server.192.168.39.245.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argocd-server
            port:
              number: 443
