apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"gateway.networking.k8s.io/v1","kind":"HTTPRoute","metadata":{"annotations":{},"name":"api-httproute","namespace":"api"},"spec":{"hostnames":["api-192.168.39.201.nip.io"],"parentRefs":[{"name":"api-gateway","namespace":"api","sectionName":"http"}],"rules":[{"backendRefs":[{"name":"api-svc","port":3000,"weight":1},{"name":"canary-api-svc","port":3000,"weight":1}],"matches":[{"path":{"type":"PathPrefix","value":"/api"}}]}]}}
  creationTimestamp: "2025-04-14T05:05:56Z"
  generation: 9
  name: api-httproute
  namespace: api
  resourceVersion: "1281588"
  uid: eeed9cdd-02a3-47d5-a072-7a064a1f657b
spec:
  hostnames:
  - api-192.168.39.201.nip.io
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: api-gateway
    namespace: api
    sectionName: http
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: api-svc
      port: 3000
      weight: 100
    - group: ""
      kind: Service
      name: canary-api-svc
      port: 3000
      weight: 0
    matches:
    - path:
        type: PathPrefix
        value: /api
status:
  parents:
  - conditions:
    - lastTransitionTime: "2025-04-14T05:05:56Z"
      message: Route was valid
      observedGeneration: 9
      reason: Accepted
      status: "True"
      type: Accepted
    - lastTransitionTime: "2025-04-14T05:05:56Z"
      message: All references resolved
      observedGeneration: 9
      reason: ResolvedRefs
      status: "True"
      type: ResolvedRefs
    controllerName: istio.io/gateway-controller
    parentRef:
      group: gateway.networking.k8s.io
      kind: Gateway
      name: api-gateway
      namespace: api
      sectionName: http
