---
apiVersion: networking.cfargotunnel.com/v1alpha1
kind: Tunnel
metadata:
  name: cf-tunnel
  namespace: playground 
spec:
  newTunnel:
    name: cf-tunnel
  size: 1
  cloudflare:
    email: __EMAIL__
    domain: __DOMAIN__
    secret: cloudflare-secrets
    accountId: __CF_ACCOUNT_ID__
  image: cloudflare/cloudflared:2024.5.0
