---
apiVersion: v1
kind: Secret
metadata:
  name: artifact-secret
  namespace: playground
type: Opaque
data:
  accessKey: __S3_ACCESS_KEY__
  secretKey: __S3_SECRET_KEY__

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: artifact-repositories
  namespace: playground
  annotations:
    workflows.argoproj.io/default-artifact-repository: dospaces
data:
  dospaces: |
    archiveLogs: false
    s3:
      endpoint: __S3_ENDPOINT__
      bucket: __BUCKET_NAME__
      region: __REGION__
      accessKeySecret:
        name: artifact-secret
        key: accessKey
      secretKeySecret:
        name: artifact-secret
        key: secretKey

