---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: container-wf-
  namespace: playground
spec:
  arguments:
    parameters:
    - name: message
      value: hello, world
  entrypoint: main
  templates:
  - name: main
    inputs:
      parameters:
      - name: message
    container: 
      image: docker/whalesay 
      imagePullPolicy: IfNotPresent
      command: [ "cowsay" ]
      args:
      - "{{ inputs.parameters.message }}"
