---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: dov-bear-wf-
  namespace: playground
spec:
  arguments:
    parameters:
    - name: replicas
      value: 2
    - name: tag
      value: v5
    - name: instanceName
      value: "dov-bear"
  serviceAccountName: playground-sa
  entrypoint: main
  templates:
  - name: main
    inputs:
      parameters:
      - name: replicas
      - name: tag
      - name: instanceName
    resource:
      action: create
      successCondition: "status.readyReplicas == {{ inputs.parameters.replicas }}"
      manifest: |
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          generateName: dov-bear-deploy-
          namespace: playground
          labels:
            app: dov-bear
            instance: "{{ inputs.parameters.instanceName }}"
            deployment: argo-workflow
          ownerReferences:
          - apiVersion: argoproj.io/v1alpha1
            kind: Workflow
            name: "{{ workflow.name }}"
            uid: "{{ workflow.uid }}"
            controller: true
        spec:
          replicas: {{ inputs.parameters.replicas }}
          selector:
            matchLabels:
              app: dov-bear-po
              deployment: argo-workflow
              instance: "{{ inputs.parameters.instanceName }}"
          template:
            metadata:
              labels:
                app: dov-bear-po
                deployment: argo-workflow
                instance: "{{ inputs.parameters.instanceName }}"
            spec:
              containers:
              - image: "chukmunnlee/dov-bear:{{ inputs.parameters.tag }}"
                name: dov-bear
                env:
                - name: INSTANCE_NAME
                  value: "{{ inputs.parameters.instanceName }}"
                - name: INSTANCE_HASH
                  valueFrom:
                    fieldRef:
                      fieldPath: status.podIP
                ports:
                - containerPort: 3000
                - containerPort: 3100

