# To make Grafana persistent (Using Statefulset)
#
grafana:
    persistence:
      enabled: true
      type: sts
      storageClassName: standard
      accessModes:
        - ReadWriteOnce
      size: 3Gi
      finalizers:
        - kubernetes.io/pvc-protection
