apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"gateway.networking.k8s.io/v1","kind":"HTTPRoute","metadata":{"annotations":{},"name":"api-httproute","namespace":"api"},"spec":{"hostnames":["api-192.168.39.200.nip.io"],"parentRefs":[{"name":"traefik-gateway","namespace":"traefik","sectionName":"web"}],"rules":[{"backendRefs":[{"name":"api-svc","port":3000},{"name":"canary-api-svc","port":3000}]}]}}
  creationTimestamp: "2025-03-07T08:27:41Z"
  generation: 5
  name: api-httproute
  namespace: api
  resourceVersion: "3574443"
  uid: 37443860-7745-4f04-9fec-010568166b33
spec:
  hostnames:
  - api-192.168.39.200.nip.io
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: traefik-gateway
    namespace: traefik
    sectionName: web
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: api-svc
      port: 3000
      weight: 100
    - group: ""
      kind: Service
      name: canary-api-svc
      port: 3000
      weight: 0
    matches:
    - path:
        type: PathPrefix
        value: /
  - backendRefs:
    - group: ""
      kind: Service
      name: canary-api-svc
      port: 3000
      weight: 0
    matches:
    - headers:
      - name: X-Version
        type: Exact
        value: v2
      path:
        type: PathPrefix
        value: /
status:
  parents:
  - conditions:
    - lastTransitionTime: "2025-03-07T08:34:50Z"
      message: ""
      observedGeneration: 5
      reason: Accepted
      status: "True"
      type: Accepted
    - lastTransitionTime: "2025-03-07T08:34:50Z"
      message: ""
      observedGeneration: 5
      reason: ResolvedRefs
      status: "True"
      type: ResolvedRefs
    controllerName: traefik.io/gateway-controller
    parentRef:
      group: gateway.networking.k8s.io
      kind: Gateway
      name: traefik-gateway
      namespace: traefik
      sectionName: web
