---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: request-latency-analysis
  namespace: api
  labels:
    app: api
    name: request-latency-analysis
spec:
  args:
  - name: job_name
  - name: service_name
  - name: url
  - name: duration
    value: 5m
  - name: percentile
    value: ".99"
  - name: latency
    value: "5"
  metrics:
  - name: request-duration-precentile
    interval: 30s
    count: 5
    successCondition: result[0] <= {{ args.latency }}
    failureLimit: 5
    provider:
      prometheus:
        address: http://prometheus-operated.monitoring.svc.cluster.local:9090
        query: |
          histogram_quantile({{ args.percentile }}, 
              sum by(le) (
                rate(
                  request_duration_ms_bucket{
                    job="{{ args.job_name }}", 
                    service="{{ args.service_name }}"
                  }[{{ args.duration }}]
                )
              )
          ) / 1000

            
