---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata: 
  name: api-smon
  namespace: api
  labels:
    release: prometheus-stack
spec:
  jobLabel: app
  selector:
    matchLabels:
      app: api
  podTargetLabels:
  - role
  endpoints:
  - targetPort: 9464
    path: /metrics
    interval: 30s

